/*
      I/B/E/S V2 PRICE TARGETS
      --------------------------------------------
      THIS QUERY RETURNS I/B/E/S DETAIL PRICE TARGET DATA.
      
      MAINTENANCE LOG
      DATE              DEVELOPER               ACTION            NOTES
      ------------------------------------------------------------------------------
      06/2015           SANDEEP  SUBASH			CREATED			ANALYST INFORMATION IS COMMENTED
																AS THERE IS NO CONFIRMATION WHETHER TO USE
																LEFT JOIN OR INNER JOIN.
																
																IT IS ALWAYS RECOMMENDED TO USE LEFT JOIN ON TREBROKERS AS BROKER DETAILS 
																WILL BE AVAILABLE BASED ON CLIENT'S BROKER ENTITLEMENT SUBSCRIPTION
																
	  02/2016			SANDEEP  SUBASH			MODIFIED		INCLUDED THE USE OF VW_SECURITYMASTERX AND VW_IBES2MAPPING

             SECURITYMASTER AND IBES2MAPPING VIEWS NEEDED TO BE INSTALLED TO RUN THIS SCRIPT.    


*/
DECLARE @ID AS VARCHAR(10)	
DECLARE @BROKER AS INT					

SET @ID = '@TOYOT17'				
SET @BROKER = -1703500341	

SELECT S.ID
	,I.ESTPERMID
	,I.IBESTICKER
	,S.NAME
	,DET.MEASURE
	,MSR.DESCRIPTION
	,DET.EFFECTIVEDATE
	,BRK.BROKERID
	,BRK.BROKERNAME
	,DET.ISPARENT
	,DET.UNITTYPE
	,CODE.DESCRIPTION AS NORMCURR
	--,DET.DEFESTVALUE
	,DET.NORMESTVALUE
	,DET.NORMESTVALUE * DET.NORMSPLITFACTOR * DET.NORMSCALE AS UNADJVALUE
	,DET.NORMSCALE
	,DET.NORMSPLITFACTOR
	,DET.PERTYPE
	,PT.DESCRIPTION AS PERTYPE_DESC
	
FROM VW_SECURITYMASTERX S

JOIN VW_IBES2MAPPING M 
	ON S.SECCODE = M.SECCODE 
	AND M.TYP = S.TYP

JOIN TREINFO I 
	 ON I.ESTPERMID = M.ESTPERMID
	
JOIN TREDETHZN DET 
	ON DET.ESTPERMID = I.ESTPERMID 
	AND DET.MEASURE = 31 -- PRICE TARGET   
	
JOIN TRECODE CODE 
	ON CODE.CODE = DET.NORMCURRPERMID -- CODE DESCRIPTION FOR CURRENCY
	AND CODE.CODETYPE = 7 -- FOR ISO3 CODE
	
LEFT JOIN TREBROKERS BRK 
	ON BRK.BROKERID = DET.BROKERID -- BROKER TABLE

JOIN TRECODE MSR --DESCRIPTIONS FOR MEASURE
	ON MSR.CODE = DET.MEASURE
	AND MSR.CODETYPE = 5
	
JOIN TRECODE PT --DESCRIPTIONS FOR PERIOD TYPE , YEARLY, QUARTERLY AND SO ON
	ON PT.CODE = DET.PERTYPE
	AND PT.CODETYPE = 2	
	
WHERE S.ID = @ID
--AND BRK.BROKERID = @BROKER -- 142 IN V1
ORDER BY DET.PERTYPE,DET.EFFECTIVEDATE
