/*
      I/B/E/S V2 DETAIL RECOMMENDATION
      --------------------------------------------
      THIS QUERY RETURNS I/B/E/S DETAIL RECOMMENDATION DATA.
      
      MAINTENANCE LOG
      DATE              DEVELOPER               ACTION            NOTES
      ------------------------------------------------------------------------------
      06/2015           SANDEEP  SUBASH			CREATED			ANALYST INFORMATION IS COMMENTED
																AS THERE IS NO CONFIRMATION WHETHER TO USE
																LEFT JOIN OR INNER JOIN.

																IT IS ALWAYS RECOMMENDED TO USE LEFT JOIN ON TREBROKERS AS BROKER DETAILS 
																WILL BE AVAILABLE BASED ON CLIENT'S BROKER ENTITLEMENT SUBSCRIPTION
																
	  02/2016			SANDEEP  SUBASH			MODIFIED		INCLUDED THE USE OF VW_SECURITYMASTERX AND VW_IBES2MAPPING

              SECURITYMASTER AND IBES2MAPPING VIEWS NEEDED TO BE INSTALLED TO RUN THIS SCRIPT.    



*/
DECLARE @ID AS VARCHAR(10)	
--DECLARE @BROKER AS INT					

SET @ID = '@TOYOT17'				
--SET @BROKER = -1703500341	

SELECT S.ID
	,I.ESTPERMID
	,I.IBESTICKER
	,S.NAME
	,DET.BROKERID
	,BRK.BROKERNAME
	--,A.ANALYSTCODE
	--,(A.FIRSTNAME+' '+A.LASTNAME) AS ANALYSTNAME
	,DET.DOMAINACTION
	,CASE WHEN DET.DOMAINACTION IS NOT NULL 
		THEN CD.DESCRIPTION 
		ELSE NULL
	END AS DOMAIN_ACT_DESC
	,DET.ISOPEN
	--,DET.ISCONFIRMED
	,DET.ISPUBLIC
	,DET.DOCTYPE
	,CASE WHEN DET.DOCTYPE IS NOT NULL 
		THEN DOCCODE.DESCRIPTION 
		ELSE NULL
	 END AS DOCTYPE_DESC
	,DET.EFFECTIVEDATE
	,C.CONFIRMDATE
	,C.EXPIREDATE AS CONFIRMENDDATE	
	,DET.EXPIREDATE
	,DET.ASCONTRIBRECCODE AS AS_CONTRIBUTED_CODE
	,DET.ASCONTRIBRECTEXT AS AS_CONTRIBUTED_CODE_TEXT
	,DET.NORMRECCODE AS NORMALIZED_CODE
	,DET.NORMRECTEXT AS NORMALIZED_CODE_TEXT
	
FROM VW_SECURITYMASTERX S

JOIN VW_IBES2MAPPING M 
	ON S.SECCODE = M.SECCODE 
	AND M.TYP = S.TYP

JOIN TREINFO I 
	 ON I.ESTPERMID = M.ESTPERMID
	
JOIN TRERECDET DET 
	ON DET.ESTPERMID = I.ESTPERMID 

LEFT JOIN TREBROKERS BRK 
	ON BRK.BROKERID = DET.BROKERID -- BROKER TABLE
	
JOIN TRECODE CD
	ON CD.CODE = DET.DOMAINACTION
	AND	CD.CODETYPE = 13
	
JOIN TRECODE DOCCODE
	ON DOCCODE.CODE = DET.DOCTYPE
	AND	DOCCODE.CODETYPE = 1 	
	
LEFT JOIN	TRERECDETCONF  C
	ON		C.ESTPERMID = DET.ESTPERMID
	AND		C.BROKERID = DET.BROKERID
	
WHERE S.ID = @ID  
--AND DET.BROKERID = @BROKER
ORDER BY DET.ANNOUNCEDATE,DET.EXPIREDATE